typedef enum {
	BLLogType_c = BLType_c,
	BLLogType_wc = BLType_wc,
	BLLogType_i8 = BLType_i8,
	BLLogType_i16 = BLType_i16,
	BLLogType_i32 = BLType_i32,
	BLLogType_i64 = BLType_i64,
	BLLogType_ui8 = BLType_ui8,
	BLLogType_ui16 = BLType_ui16,
	BLLogType_ui32 = BLType_ui32,
	BLLogType_ui64 = BLType_ui64,
	BLLogType_f = BLType_f,
	BLLogType_d = BLType_d,
	BLLogType_fc = BLType_fc,
	BLLogType_dc = BLType_dc,
	BLLogType_ptr = BLType_ptr,
	BLLogType_Array_c,
	BLLogType_Array_wc,
	BLLogType_Array_i8,
	BLLogType_Array_i16,
	BLLogType_Array_i32,
	BLLogType_Array_i64,
	BLLogType_Array_ui8,
	BLLogType_Array_ui16,
	BLLogType_Array_ui32,
	BLLogType_Array_ui64,
	BLLogType_Array_f,
	BLLogType_Array_d,
	BLLogType_Array_fc,
	BLLogType_Array_dc,
	BLLogType_Array_ptr,
} BLLogType, *PBLLogType;

const wchar_t* BLLogType_Labels[] = {
	L"BLLogType_c",
	L"BLLogType_wc",
	L"BLLogType_i8",
	L"BLLogType_i16",
	L"BLLogType_i32",
	L"BLLogType_i64",
	L"BLLogType_ui8",
	L"BLLogType_ui16",
	L"BLLogType_ui32",
	L"BLLogType_ui64",
	L"BLLogType_f",
	L"BLLogType_d",
	L"BLLogType_fc",
	L"BLLogType_dc",
	L"BLLogType_ptr",
	L"BLLogType_Array_c",
	L"BLLogType_Array_wc",
	L"BLLogType_Array_i8",
	L"BLLogType_Array_i16",
	L"BLLogType_Array_i32",
	L"BLLogType_Array_i64",
	L"BLLogType_Array_ui8",
	L"BLLogType_Array_ui16",
	L"BLLogType_Array_ui32",
	L"BLLogType_Array_ui64",
	L"BLLogType_Array_f",
	L"BLLogType_Array_d",
	L"BLLogType_Array_fc",
	L"BLLogType_Array_dc",
	L"BLLogType_Array_ptr",
};
